services:
  server:
    image: server
    depends_on:
      - mosquitto
    ports:
      - "9191:9191"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "8883:8883"
      - "8884:8884"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/acl:/mosquitto/acl
      - ./mosquitto/cert:/mosquitto/cert
      - ./cert:/cert